### ISSUE TITLE
Support 1.19.3

### ISSUE THREAD

**Issue by ghost** [BukkitFabric/bukkit4fabric#386]
Will there be support for 1.19.3?

**Comment by xiaoyang5202480** [comment]
I'dont know

**Comment by TwoPointInfinity** [comment]
i think 1.19.3 support is the least of the issues in this mod. Cardboard literally doesn't work yet for even the versions they supposedly support. this mod is extremely complicated and it doesn't seem to get consistent updates.

> I'dont know

why did you even reply to this? What a useless thing to comment.

**Comment by lonelysam3** [comment]
> i think 1.19.3 support is the least of the issues in this mod. Cardboard literally doesn't work yet for even the versions they supposedly support. this mod is extremely complicated and it doesn't seem to get consistent updates.
> 
> > I'dont know
> 
> why did you even reply to this? What a useless thing to comment.


Probably xiaoyang5202480 is a pupil(primary school student) and has nothing to do but waste other people's time.
And back to this mod,IsaiahPatton may had already stopped to develop because the low sponsorship.
As you can see in the change log in the default issue.IsaiahPatton had never update the default issue since he or she created the issue in 2020.

**Comment by samuelh2005** [comment]
There isn't official 1.19.x support yet. However, it is being worked on, See #362

**Comment by RichardIsSoarx** [comment]
@isaiahpatton Can we close this ticket. This is frankly a non issue. @largenton Support for 1.19.3 will come when announced.
